Controllers/DataController.cs
using IntexMummy11.Data;
using IntexMummy11.Models;
using IntexMummy11.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace IntexMummy11.Controllers
{
    public class DataController : Controller
    {

        private ebdbContext ebdbContext { get; set; }
        private IBurialRepository repo;

        public DataController(IBurialRepository temp)
        {
            repo = temp;
        }

        [HttpGet]
        public IActionResult BurialList(int pageNum=1)
        {
            int pageSize = 50;
            var x = new MinitableViewModel
            {
                Data = repo.Data
                .Skip((pageNum - 1) * pageSize)
                .Take(pageSize),

                PageInfo = new PageInfo
                {
                    TotalNumBurials =
                    repo.Data.Count(),
                    BurialsPerPage = pageSize,
                    CurrentPage = pageNum
                }
            };

            return View(x);
            
        }


        [HttpPost]
        public IActionResult BurialList(MinitableViewModel mtvm, int pageNum = 1)
        {
            int pageSize = 50;
            
            var x = new MinitableViewModel
            {
                Data = repo.Data
                .Where(s => s.Sex == mtvm.SexFilter || mtvm.SexFilter == null)
                .Where(a => a.Ageatdeath == mtvm.AgeFilter || mtvm.AgeFilter == null)
                .Where(c => c.ColorValue.Contains("/" + mtvm.TextileColorFilter + "/") || mtvm.TextileColorFilter == null)
                .Where(dmin => Convert.ToDecimal(dmin.Depth) >= Convert.ToDecimal(mtvm.BurialDepthFilterMin))
                .Where(dmax => Convert.ToDecimal(dmax.Depth) <= Convert.ToDecimal(mtvm.BurialDepthFilterMax))
                .Where(hd => hd.Headdirection == mtvm.HeadDirectionFilter || mtvm.HeadDirectionFilter == null)
                .Where(ts => ts.TextilefunctionValue.Contains("/" + mtvm.TextileStructureFilter + "/") || mtvm.TextileStructureFilter == null)
                .Where(tf => tf.TextilefunctionValue.Contains("/" + mtvm.TextileFunctionFilter + "/") || mtvm.TextileFunctionFilter == null)
                .Where(hc => hc.Haircolor == mtvm.HairColorFilter || mtvm.HairColorFilter == null)
                .Where(bw => bw.Wrapping == mtvm.BurialWrappingFilter || mtvm.BurialWrappingFilter == null)
                .Where(es => es.TextilefunctionValue.Contains("/" + mtvm.EstimatedStatureFilter + "/") || mtvm.EstimatedStatureFilter == null)
                .Where(fb => fb.Facebundles == mtvm.FaceBundleFilter || mtvm.FaceBundleFilter == null)
                .Skip((pageNum - 1) * pageSize)
                .Take(pageSize),

                PageInfo = new PageInfo
                {
                    TotalNumBurials =
                    (mtvm.SexFilter == null && mtvm.AgeFilter == null && mtvm.FaceBundleFilter == null && mtvm.TextileColorFilter == null && mtvm.HeadDirectionFilter == null && mtvm.TextileStructureFilter == null && mtvm.TextileFunctionFilter == null && mtvm.HairColorFilter == null && mtvm.BurialWrappingFilter == null && mtvm.EstimatedStatureFilter == null ?
                    repo.Data.Count() :
                    repo.Data.Where(x => x.Sex == mtvm.SexFilter)
                    .Where(a => a.Ageatdeath == mtvm.AgeFilter)
                    .Where(c => c.ColorValue.Contains("/"+ mtvm.TextileColorFilter + "/"))
                    .Where(dmin => Convert.ToDecimal(dmin.Depth) >= Convert.ToDecimal(mtvm.BurialDepthFilterMin))
                    .Where(dmax => Convert.ToDecimal(dmax.Depth) <= Convert.ToDecimal(mtvm.BurialDepthFilterMax))
                    .Where(hd => hd.Headdirection == mtvm.HeadDirectionFilter)
                    .Where(ts => ts.TextilefunctionValue.Contains("/" + mtvm.TextileStructureFilter + "/"))
                    .Where(tf => tf.TextilefunctionValue.Contains("/" + mtvm.TextileFunctionFilter + "/"))
                    .Where(hc => hc.Haircolor == mtvm.HairColorFilter)
                    .Where(bw => bw.Wrapping == mtvm.BurialWrappingFilter)
                    .Where(tf => tf.TextilefunctionValue.Contains("/" + mtvm.EstimatedStatureFilter + "/"))
                    .Where(fb => fb.Facebundles == mtvm.FaceBundleFilter)
                    .Count()),
                    BurialsPerPage = pageSize,
                    CurrentPage = pageNum
                }
            };

            return View(x);

        }

        public IActionResult BurialPredictions()
        {
            return View();
        }

        public IActionResult BurialInsights()
        {
            var x = new BurialViewModel
            {
                Burials = repo.Burials
                /*.Where(b => b.Category == catergoryName || catergoryName == null)
                .OrderBy(b => b.Title)
                .Skip((pageNum - 1) * pageSize)*/
            };
            return View(x);
        }

        //Creating Burial Main record
        [HttpGet]
        public IActionResult CreateBurialMain()
        {
            //Create a new BurialMain record and pass it to  the view to add it

            return View(new Burialmain());

        }

        [HttpGet]
        public IActionResult CreateBurialMain2(Burialmain yuh)
        {
            //Create a new BurialMain record and pass it to  the view to add it

            return View("CreateBurialMain2", yuh);

        }



        [HttpPost]
        public IActionResult CreateBurialMain(Burialmain newlyCreatedBurialMain)
        {
            //Create a new BurialMain record and pass it to  the view to add it

            //Could validate some data here with a post or something.
            if (ModelState.IsValid)
            {

                //Find the next id
                repo.Burials.Select(col => col.Id).Max();
                Burialmain lastRecord = repo.Burials.OrderByDescending(col => col.Id).FirstOrDefault();
                long nextID = lastRecord.Id + 1;


                // Set property values from the newlyCreatedBurialMain parameter
                Burialmain addme = new Burialmain
                {

                    Id = nextID,
                    Squarenorthsouth = newlyCreatedBurialMain.Squarenorthsouth,
                    Headdirection = newlyCreatedBurialMain.Headdirection,
                    Sex = newlyCreatedBurialMain.Sex,
                    Northsouth = newlyCreatedBurialMain.Northsouth,
                    Depth = newlyCreatedBurialMain.Depth,
                    Eastwest = newlyCreatedBurialMain.Eastwest,
                    Adultsubadult = newlyCreatedBurialMain.Adultsubadult,
                    Facebundles = newlyCreatedBurialMain.Facebundles,
                    Southtohead = newlyCreatedBurialMain.Southtohead,
                    Preservation = newlyCreatedBurialMain.Preservation,
                    Fieldbookpage = newlyCreatedBurialMain.Fieldbookpage,
                    Squareeastwest = newlyCreatedBurialMain.Squareeastwest,
                    Goods = newlyCreatedBurialMain.Goods,
                    Text = newlyCreatedBurialMain.Text,
                    Wrapping = newlyCreatedBurialMain.Wrapping,
                    Haircolor = newlyCreatedBurialMain.Haircolor,
                    Westtohead = newlyCreatedBurialMain.Westtohead,
                    Samplescollected = newlyCreatedBurialMain.Samplescollected,
                    Area = newlyCreatedBurialMain.Area,
                    Burialid = newlyCreatedBurialMain.Burialid, //May be null
                    Length = newlyCreatedBurialMain.Length,
                    Burialnumber = newlyCreatedBurialMain.Burialnumber,
                    Dataexpertinitials = newlyCreatedBurialMain.Dataexpertinitials,
                    Westtofeet = newlyCreatedBurialMain.Westtofeet,
                    Ageatdeath = newlyCreatedBurialMain.Ageatdeath,
                    Southtofeet = newlyCreatedBurialMain.Southtofeet,
                    Excavationrecorder = newlyCreatedBurialMain.Excavationrecorder,
                    Photos = newlyCreatedBurialMain.Photos,
                    Hair = newlyCreatedBurialMain.Hair,
                    Burialmaterials = newlyCreatedBurialMain.Burialmaterials,
                    Dateofexcavation = newlyCreatedBurialMain.Dateofexcavation, //Datetime type // may be null
                    Fieldbookexcavationyear = newlyCreatedBurialMain.Fieldbookexcavationyear,
                    Clusternumber = newlyCreatedBurialMain.Clusternumber,
                    Shaftnumber = newlyCreatedBurialMain.Shaftnumber
                };


                // Add the new object to the database context
                repo.Add(addme);
                // Save the changes to the database
                repo.Save();
                


            }
            int pageNum = 1;
            int pageSize = 50;
            var x = new MinitableViewModel
            {
                Data = repo.Data
                .Skip((pageNum - 1) * pageSize)
                .Take(pageSize),

                PageInfo = new PageInfo
                {
                    TotalNumBurials =
                    repo.Data.Count(),
                    BurialsPerPage = pageSize,
                    CurrentPage = pageNum
                }
            };






            return RedirectToAction("BurialList");

        }


        [HttpGet]
        public IActionResult Edit(long burialmainid)
        {
            // Retrieve the BurialMain record to be edited
            var burialMain = repo.Burials.Single(b => b.Id == burialmainid);
            if (burialMain == null)
            {
                // Handle case where record is not found
                return NotFound();
            }

Views/Data/BurialDetails.cshtml
@{
    ViewData["Title"] = "Burial Details";
}
@model IntexMummy11.Models.ViewModels.MinitableViewModel

<div class="text-center">
    <div class="mx-scrollcontainer-top">
        <img class="mx-image mx-name-image1 img-responsive" src="~/img/EgyptPic.jpg" role="presentation" width="100%" border="0">
    </div>
</div>
<div class="bg-dark text-white p-2">
    <div class="container-fluid">
        <div class="row">
            <div class="col navbar-brand">Burial Data</div>
            <a asp-action="CreateBurialMain"> <div class="col float-right btn-outline-light navbar-brand">  Add record </div> </a>
        </div>
    </div>
</div>


<div class="card card-outline-primary m-1 p-1">
    <form method="post" asp-page="/Description" class="form-check-inline">
        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end" asp-controller="Data" asp-action="BurialList">Back to Burials</button>
        </span>
    </form>
</div>
    
<div>

    @foreach (Minitable m in Model.Data)
    {
    <div class="card card-outline-primary m-1 p-1">
        <div class="bg-light p-1">
            <div class="card-text p-1" style="border: 20px solid black; padding: 20px;">
                <ul>
                    <lh class="font-weight-bold">Burial ID: @m.Burialmainid</lh>
                    <li>Description:@m.Description</li>
                    <li>Sex: @m.Sex</li>
                    <li>Age: @m.Ageatdeath</li>
                    <li>Head Direction: @m.Headdirection</li>
                    <li>Depth:@m.Depth</li>
                    <li>Text: @m.Text</li>
                    <li>Text: @m.Length</li>
                    <li>Square East/West: @m.Squareeastwest</li>
                    <li>Square North/South: @m.Squarenorthsouth @m.Northsouth</li>
                    <li>South to Head: @m.Southtohead</li>
                    <li>South to Feet: @m.Southtofeet</li>
                    <li>Wrapping: @m.Wrapping</li>
                    <li>Hair Color: @m.Haircolor</li>
                    <li>Area: @m.Area</li>
                    <li>Length: @m.Length</li>


                </ul>
            </div>
        </div>
    </div>
    }
</div>

Views/Data/BurialInsights.cshtml
@{
    ViewData["Title"] = "Burial Insights";
}

@model IntexMummy11.Models.ViewModels.BurialViewModel

<div class="text-center">
    <div class="mx-scrollcontainer-top">
        <img class="mx-image mx-name-image1 img-responsive" src="~/img/EgyptPic.jpg" role="presentation" width="100%" border="0">
    </div>
    <h3>Welcome to the Burial Insights Page</h3>
    <p>
        Here, view an unsupervised analysis report on the connection between depth and position of tombs with age
        Or our awesome data
    </p>

    <h1>3D Visual of Depth at Different Coordinates</h1>
    <img src="~/img/Screen Shot 2023-04-14 at 10.38.26 AM.png" alt="Burial Heat Map" width="650" height="500" /> <br /><br />

    <h1>Unsupervised Heat Map</h1>
    <img src="~/img/Screen Shot 2023-04-13 at 4.04.34 PM.png" alt="Burial Heat Map" width="650" height="500" /> <br /><br />

    <h1>Burial Site Visualization</h1>
    <img src="~/img/Screen Shot 2023-04-13 at 7.57.43 PM.png" alt="Burial Site Visualization" width="600" height="500" />
</div>

Views/Data/BurialList.cshtml
@{
    ViewData["Title"] = "Burial List";
}
@model IntexMummy11.Models.ViewModels.MinitableViewModel
<div class="text-center">
    <div class="mx-scrollcontainer-top">
        <img class="mx-image mx-name-image1 img-responsive" src="~/img/EgyptPic.jpg" role="presentation" width="100%" border="0">
    </div>
    <br />
    <h3>Welcome to the Burial List Page</h3>
    <p>
        Here, view and filter all of the burials in the database to analyze the data.
    </p>
</div>
<div class="bg-dark text-white p-2">
    <div class="container-fluid">
        <div class="row">
            <div class="col navbar-brand">Burial Data</div>
            @if (User.Identity.IsAuthenticated) { 
            <a asp-action="CreateBurialMain"> <div class="col float-right btn-outline-light navbar-brand">  Add record </div> </a>
            }
        </div>
    </div>
</div>
<div>
    @*<div class="row m-1 p-1">
            <vc:filtering></vc:filtering>
        </div>*@

    <div>
        <form method="post">
            <label asp-for="SexFilter" type="hidden">Sex:</label>
            <select asp-for="SexFilter">
                <option value="">Any Sex</option>
                <option value="M">Male</option>
                <option value="F">Female</option>
            </select>
            <br />
            <label asp-for="AgeFilter" type="hidden">Age:</label>
            <select asp-for="AgeFilter">
                <option value="">Any Age</option>
                <option value="A">Adult (year 15+)</option>
                <option value="C">Child (years 3-15)</option>
                <option value="I">Infant (years 1-3)</option>
                <option value="N">Newborn (year 0-1)</option>
                <option value="U">Unknown</option>
            </select>
            <br />
            <label asp-for="TextileColorFilter" type="hidden">Textile Color:</label>
            <input asp-for="TextileColorFilter" />
            <br />
            <label asp-for="TextileStructureFilter" type="hidden">Textile Structure:</label>
            <input asp-for="TextileStructureFilter" />
            <br />
            <label asp-for="BurialDepthFilterMin" type="hidden">Burial Depth Min:</label>
            <input asp-for="BurialDepthFilterMin" type="number" step="0.01" value="0">
            <br />
            <label asp-for="BurialDepthFilterMax" type="hidden">Burial Depth Max:</label>
            <input asp-for="BurialDepthFilterMax" type="number" step="0.01" value="5">
            <br />
            <label asp-for="TextileFunctionFilter" type="hidden">Textile Function:</label>
            <input asp-for="TextileFunctionFilter" />
            <br />
            <label asp-for="HairColorFilter" type="hidden">Hair Color:</label>
            <select asp-for="HairColorFilter">
                <option value="">Any Hair Color</option>
                <option value="B">Brown/Dark Brown/Lt Brown</option>
                <option value="K">Black</option>
                <option value="A">Brown-Red</option>
                <option value="R">Red/Red-Bl</option>
                <option value="D">Blond</option>
                <option value="U">Unknown</option>
            </select>
            <br />
            <label asp-for="EstimatedStatureFilter" type="hidden">Estimated Stature:</label>
            <input asp-for="EstimatedStatureFilter" />
            <br />
            <label asp-for="HeadDirectionFilter" type="hidden">Head Direction:</label>
            <select asp-for="HeadDirectionFilter">
                <option value="">Any Head Direction</option>
                <option value="N">North</option>
                <option value="S">South</option>
                <option value="E">East</option>
                <option value="W">West</option>
            </select>
            <br />
            <label asp-for="BurialWrappingFilter" type="hidden">Hair Color:</label>
            <select asp-for="BurialWrappingFilter">
                <option value="">Any Burial Wrapping</option>
                <option value="W">Full or nearly full wrapping remains</option>
                <option value="H">Partial wrapping remain</option>
                <option value="B">Bones and/or only partial remnants of wrapping remains</option>
                <option value="U">Unknown</option>
            </select>
            <br />
            <label asp-for="FaceBundleFilter" type="hidden">Face Bundle:</label>
            <select asp-for="FaceBundleFilter">
                <option value="">Select</option>
                <option value="Y">Yes</option>
                <option>No</option>
            </select>
            <br />




            <button type="submit">Apply Filters</button>
        </form>
    </div>

    <table class="table table-bordered table-striped table-hover col-10">
        <thead>
            <tr>
                <th>Burial ID</th>
                <th>Head Direction</th>
                <th>Depth</th>
                <th>Text</th>
                <th>Wrapping</th>
                <th>Age</th>
                <th>Excavation Year</th>
                <th>Details</th>

                @if (User.Identity.IsAuthenticated)
                {
                    <th>Edit</th>
                    <th>Delete</th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (Minitable m in Model.Data)
            {
            <tr>
                <td>@m.Burialmainid</td>
                <td>@m.Headdirection</td>
                <td>@m.Depth</td>
                <td>@m.Text</td>
                <td>@m.Wrapping</td>
                <td>@m.Adultsubadult</td>
                <td>@m.Fieldbookexcavationyear</td>
                <td>
                    <form method="post" asp-page="/Description" class="form-check-inline">
                        <input type="hidden" asp-for="@Model.BurialIDForDescription" value="@m.Burialmainid" />
                        <span class="card-text">
                            <button type="submit" class="btn btn-success btn-sm float-end" asp-controller="Data" asp-action="BurialDetails">View Details</button>

                        </span>

                    </form>
                </td>
                @if (User.Identity.IsAuthenticated)
                {
                    <td><a asp-controller="Data" asp-action="Edit" asp-route-burialmainid="@m.Burialmainid">Edit</a></td>
                    <td><a asp-controller="Data" asp-action="Delete" asp-route-id="@m.Burialmainid">Delete</a></td>
                }
                    @*<td><a asp-controller="Data" asp-action="Delete" asp-route-id="@m.Burialmainid">Delete</a></td>*@
                    @*<td>
                <form method="get" class="form-check-inline">
                    <input type="hidden" asp-for="@m.Burialmainid" value="@m.Burialmainid" />
                    <span class="card-text">
                        <button type="submit" class="btn btn-success btn-sm float-end" asp-controller="Data" asp-action="Delete">Delete</button>

                    </span>

                </form>
            </td>*@
                </tr>
            }
        </tbody>
    </table>
</div>
<div page-blah="@Model.PageInfo" page-action="BurialList" page-classes-enabled="true" page-class="btn" page-class-normal="btn-outline-dark"
     page-class-selected="btn-primary" class="btn-group pull-right m-1">
</div>

Views/Data/CreateBurialMain.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IntexMummy11.Models.Burialmain

<div class="text-center">
    <div class="mx-scrollcontainer-top">
        <img class="mx-image mx-name-image1 img-responsive" src="~/img/EgyptPic.jpg" role="presentation" width="100%" border="0">
    </div>
    <h3>Add a Burial Record</h3>
    <p>
        Currently, we can only add to a single table at a time
    </p>

    <form id="prediction-form" method="post" asp-controller="Data" asp-action="CreateBurialMain">

        <div asp-validation-summary="All" class="text-danger"></div>
        <h4>.....</h4>

        <h4>Measurements</h4>

        <div class="form-group">
            <input type="hidden" asp-for="Id"id="id" name="id" value="@Model.Id">
        </div>
        <div class="form-group">
            <label asp-for="Squarenorthsouth">Square North to South</label>
            <input asp-for="Squarenorthsouth"type="text" id="squarenorthsouth" name="squarenorthsouth">
        </div>
        <div class="form-group">
            <label asp-for="Headdirection">Head Direction</label>
            <input asp-for="Headdirection"type="text" id="headdirection" name="headdirection">
        </div>
        <div class="form-group">
            <label asp-for="Sex">Sex</label>
            <input asp-for="Sex"type="text" id="sex" name="sex">
        </div>
        <div class="form-group">
            <label asp-for="Northsouth">North to South</label>
            <input asp-for="Northsouth"type="text" id="northsouth" name="northsouth">
        </div>
        <div class="form-group">
            <label asp-for="Depth">Depth</label>
            <input asp-for="Depth"type="text" id="depth" name="depth">
        </div>
        <div class="form-group">
            <label asp-for="Eastwest">East to West</label>
            <input asp-for="Eastwest"type="text" id="eastwest" name="eastwest">
        </div>
        <div class="form-group">
            <label asp-for="Adultsubadult">Adult/Subadult</label>
            <input asp-for="Adultsubadult"type="text" id="adultsubadult" name="adultsubadult">
        </div>
        <div class="form-group">
            <label asp-for="Facebundles">Face Bundles</label>
            <input asp-for="Facebundles"type="text" id="facebundles" name="facebundles">
        </div>
        <div class="form-group">
            <label asp-for="Southtohead">South to Head</label>
            <input asp-for="Southtohead"type="text" id="southtohead" name="southtohead">
        </div>
        <div class="form-group">
            <label asp-for="Preservation">Preservation</label>
            <input asp-for="Preservation"type="text" id="preservation" name="preservation">
        </div>
        <div class="form-group">
            <label asp-for="Fieldbookpage">Field Book Page</label>
            <input asp-for="Fieldbookpage"type="text" id="fieldbookpage" name="fieldbookpage">
        </div>
        <div class="form-group">
            <label asp-for="Squareeastwest">Square East to West</label>
            <input asp-for="Squareeastwest"type="text" id="squareeastwest" name="squareeastwest">
        </div>
        <div class="form-group">
            <label asp-for="Goods">Goods</label>
            <input asp-for="Goods"type="text" id="goods" name="goods">
        </div>
        <div class="form-group">
            <label asp-for="Text">Text</label>
            <input asp-for="Text"type="text" id="text" name="text">
        </div>
        <div class="form-group">
            <label asp-for="Wrapping">Wrapping</label>
            <input asp-for="Wrapping"type="text" id="wrapping" name="wrapping">
        </div>
        <div class="form-group">
            <label asp-for="Haircolor">Hair Color</label>
            <input asp-for="Haircolor"type="text" id="haircolor" name="haircolor">
        </div>
        <div class="form-group">
            <label asp-for="Westtohead">West to Head</label>
            <input asp-for="Westtohead"id="westtohead" name="westtohead" />
        </div>
        <div class="form-group">
            <label asp-for="Samplescollected">Samples Collected</label>
            <input asp-for="Samplescollected"id="samplescollected" name="samplescollected" />
        </div>
        <div class="form-group">
            <label asp-for="Area">Area</label>
            <input asp-for="Area"id="area" name="area" />
        </div>
        <div class="form-group">
            <label asp-for="Burialid">Burial ID</label>
            <input asp-for="Burialid"id="burialid" name="burialid" />
        </div>
        <div class="form-group">
            <label asp-for="Length">Length</label>
            <input asp-for="Length"id="length" name="length" />
        </div>
        <div class="form-group">
            <label asp-for="Burialnumber">Burial Number</label>
            <input asp-for="Burialnumber"id="burialnumber" name="burialnumber" />
        </div>
        <div class="form-group">
            <label asp-for="Dataexpertinitials">Data Expert Initials</label>
            <input asp-for="Dataexpertinitials"id="dataexpertinitials" name="dataexpertinitials" />
        </div>
        <div class="form-group">
            <label asp-for="Westtofeet">West to Feet</label>
            <input asp-for="Westtofeet"id="westtofeet" name="westtofeet" />
        </div>
        <div class="form-group">
            <label asp-for="Ageatdeath">Age at Death</label>
            <input asp-for="Ageatdeath"id="ageatdeath" name="ageatdeath" />
        </div>
        <div class="form-group">
            <label asp-for="Southtofeet">South to Feet</label>
            <input asp-for="Southtofeet"id="southtofeet" name="southtofeet" />
        </div>
        <div class="form-group">
            <label asp-for="Excavationrecorder">Excavation Recorder</label>
            <input asp-for="Excavationrecorder"id="excavationrecorder" name="excavationrecorder" />
        </div>
        <div class="form-group">
            <label asp-for="Photos">Photos</label>
            <input asp-for="Photos"id="photos" name="photos" />
        </div>
        <div class="form-group">
            <label asp-for="Hair">Hair</label>
            <input asp-for="Hair"id="hair" name="hair" />
        </div>
        <div class="form-group">
            <label asp-for="Burialmaterials">Burial Materials</label>
            <input asp-for="Burialmaterials"id="burialmaterials" name="burialmaterials" />
        </div>
        <div class="form-group">
            <label asp-for="Dateofexcavation">Date of Excavation</label>
            <input asp-for="Dateofexcavation"type="date" id="dateofexcavation" name="dateofexcavation" />
        </div>
        <div class="form-group">
            <label asp-for="Fieldbookexcavationyear">Field Book Excavation Year</label>
            <input asp-for="Fieldbookexcavationyear"id="fieldbookexcavationyear" name="fieldbookexcavationyear" />
        </div>
        <div class="form-group">
            <label asp-for="Clusternumber">Cluster Number</label>
            <input asp-for="Clusternumber"id="clusternumber" name="clusternumber" />
        </div>
        <div class="form-group">
            <label asp-for="Shaftnumber">Shaft Number</label>
            <input asp-for="Shaftnumber"id="shaftnumber" name="shaftnumber" />
        </div>


        @*<div class="form-group">
                <label>Area Direction</label>
                <select>
                    <option value="area_NE">area_NE</option>
                    <option value="area_NNW">area_NNW</option>
                    <option value="area_NW">area_NW</option>
                    <option value="area_SE">area_SE</option>
                    <option value="area_SE">area_SW</option>
                </select>
            </div>*@

        <div class="float-end">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
</div>

Views/Data/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Delete Burial";
}

@model IntexMummy11.Models.Burialmain

<h2>Confirm Deletion</h2>

<h3>Are you sure you want to delete the record for the burial with id:</h3>
<div>

    @*@foreach (Minitable m in Model.Data)
        {
            <div class="card card-outline-primary m-1 p-1">
                <div class="bg-light p-1">
                    <div class="card-text p-1" style="border: 20px solid black; padding: 20px;">
                        <ul>
                            <lh class="font-weight-bold">Burial ID: @m.Burialmainid</lh>
                        </ul>
                    </div>
                </div>
            </div>
        }*@


</div>
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-light p-1">
        <div class="card-text p-1" style="border: 20px solid black; padding: 20px;">
            <ul>
                <lh class="font-weight-bold">Do you want to delete Burial ID: @Model.Id?</lh>
            </ul>
        </div>
    </div>
</div>

<form method="post" asp-controller="Data" asp-action="DeletePost">
    <button type="submit">Delete</button>

    <a asp-controller="Data" asp-action="BurialList" class="btn btn-primary">Cancel</a>
    
    <input type="hidden" name="burialid" value="@Model.Id" />
        
</form>